import { app } from 'electron';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { SessionRecord, SessionSummary } from '../../shared/context';

/**
 * Persistent store of previous AI Chat sessions (docs/context-mcp-design §4.1) —
 * marudesk had no chat history before. When a conversation ends (or is cleared
 * for a new one), the loop snapshots the transcript here so the agent's
 * `list_sessions` / `read_session` context tools — and, later, a sessions UI —
 * can recall it.
 *
 * Layout under userData/sessions/: one `<id>.json` per {@link SessionRecord}, plus
 * an `index.json` of {@link SessionSummary} rows for a cheap list without reading
 * every transcript. Bounded to {@link MAX_SESSIONS}; the oldest are pruned (file +
 * index row) on save. All IO is best-effort — a failure never breaks a turn.
 */

const MAX_SESSIONS = 200;

function dir(): string {
  return path.join(app.getPath('userData'), 'sessions');
}
function indexPath(): string {
  return path.join(dir(), 'index.json');
}
function recordPath(id: string): string {
  // id is generated by the loop (uid('session-…')) — never user input — but pin
  // it to the directory anyway so a malformed id can't escape it.
  return path.join(dir(), `${path.basename(id)}.json`);
}

async function readIndex(): Promise<SessionSummary[]> {
  try {
    const raw = await fs.readFile(indexPath(), 'utf8');
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as SessionSummary[]) : [];
  } catch {
    return [];
  }
}

async function writeIndex(rows: SessionSummary[]): Promise<void> {
  await fs.mkdir(dir(), { recursive: true });
  await fs.writeFile(indexPath(), JSON.stringify(rows, null, 2), 'utf8');
}

/** Persist (or replace by id) a session, prepend its summary, prune the oldest. */
export async function saveSession(record: SessionRecord): Promise<void> {
  try {
    await fs.mkdir(dir(), { recursive: true });
    await fs.writeFile(recordPath(record.id), JSON.stringify(record), 'utf8');
    const summary: SessionSummary = {
      id: record.id,
      title: record.title,
      createdAt: record.createdAt,
      updatedAt: record.updatedAt,
      provider: record.provider,
      model: record.model,
      messageCount: record.messageCount,
    };
    const rows = [summary, ...(await readIndex()).filter((r) => r.id !== record.id)];
    rows.sort((a, b) => b.updatedAt - a.updatedAt);
    const kept = rows.slice(0, MAX_SESSIONS);
    // Prune transcript files that fell off the end of the index.
    for (const row of rows.slice(MAX_SESSIONS)) {
      await fs.rm(recordPath(row.id), { force: true }).catch(() => {});
    }
    await writeIndex(kept);
  } catch {
    // best-effort — losing a session record must never break the turn
  }
}

/** Recent sessions, newest first (summaries only). */
export async function listSessions(limit = 30): Promise<SessionSummary[]> {
  const rows = await readIndex();
  rows.sort((a, b) => b.updatedAt - a.updatedAt);
  return rows.slice(0, Math.max(1, Math.min(limit, MAX_SESSIONS)));
}

/** A full saved session by id, or null when not found / unreadable. */
export async function readSession(id: string): Promise<SessionRecord | null> {
  try {
    const raw = await fs.readFile(recordPath(id), 'utf8');
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === 'object' ? (parsed as SessionRecord) : null;
  } catch {
    return null;
  }
}

/** Delete a saved session: its transcript file and its index row. Best-effort. */
export async function deleteSession(id: string): Promise<boolean> {
  try {
    await fs.rm(recordPath(id), { force: true });
    const rows = (await readIndex()).filter((r) => r.id !== id);
    await writeIndex(rows);
    return true;
  } catch {
    return false;
  }
}
